[nodemon] 3.1.0
[nodemon] to restart at any time, enter`rs`
[nodemon] watching path(s): *.*
    [nodemon] watching extensions: js, mjs, cjs, json
    [nodemon] starting`node ./bin/www`
GET / js / svg / person.svg 304 25.733 ms - -
    GET / js / svg / person - add.svg 304 36.023 ms - -
        GET / js / svg / mail.svg 304 39.584 ms - -
            GET / js / svg / lock - closed.svg 304 35.413 ms - -
                GET / js / svg / id - card.svg 304 34.237 ms - -
                    REGISTER: <ref * 2 > IncomingMessage {
    _readableState: ReadableState {
        state: 137270,
            highWaterMark: 16384,
                buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
            pipes: [],
                flowing: true,
                    errored: null,
                        defaultEncoding: 'utf8',
                            awaitDrainWriters: null,
                                decoder: null,
                                    encoding: null,
                                        [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] { },
    _eventsCount: 0,
        _maxListeners: undefined,
            socket: <ref * 1 > Socket {
        connecting: false,
            _hadError: false,
                _parent: null,
                    _host: null,
                        _closeAfterHandlingError: false,
                            _readableState: ReadableState {
            state: 4184,
                highWaterMark: 16384,
                    buffer: BufferList { head: null, tail: null, length: 0 },
            length: 0,
                pipes: [],
                    flowing: true,
                        errored: null,
                            defaultEncoding: 'utf8',
                                awaitDrainWriters: null,
                                    decoder: null,
                                        encoding: null,
                                            [Symbol(kPaused)]: false
        },
        _events: [Object: null prototype] {
            end: [Array],
                timeout: [Function: socketOnTimeout],
                    data: [Function: bound socketOnData],
                        error: [Array],
                            close: [Array],
                                drain: [Function: bound socketOnDrain],
                                    resume: [Function: onSocketResume],
                                        pause: [Function: onSocketPause]
        },
        _eventsCount: 8,
            _maxListeners: undefined,
                _writableState: WritableState {
            objectMode: false,
                highWaterMark: 16384,
                    finalCalled: false,
                        needDrain: false,
                            ending: false,
                                ended: false,
                                    finished: false,
                                        destroyed: false,
                                            decodeStrings: false,
                                                defaultEncoding: 'utf8',
                                                    length: 0,
                                                        writing: false,
                                                            corked: 0,
                                                                sync: true,
                                                                    bufferProcessing: false,
                                                                        onwrite: [Function: bound onwrite],
                                                                            writecb: null,
                                                                                writelen: 0,
                                                                                    afterWriteTickInfo: null,
                                                                                        buffered: [],
                                                                                            bufferedIndex: 0,
                                                                                                allBuffers: true,
                                                                                                    allNoop: true,
                                                                                                        pendingcb: 0,
                                                                                                            constructed: true,
                                                                                                                prefinished: false,
                                                                                                                    errorEmitted: false,
                                                                                                                        emitClose: false,
                                                                                                                            autoDestroy: true,
                                                                                                                                errored: null,
                                                                                                                                    closed: false,
                                                                                                                                        closeEmitted: false,
                                                                                                                                            [Symbol(kOnFinished)]: []
        },
        allowHalfOpen: true,
            _sockname: null,
                _pendingData: null,
                    _pendingEncoding: '',
                        server: Server {
            maxHeaderSize: undefined,
                insecureHTTPParser: undefined,
                    requestTimeout: 300000,
                        headersTimeout: 60000,
                            keepAliveTimeout: 5000,
                                connectionsCheckingInterval: 30000,
                                    joinDuplicateHeaders: undefined,
                                        rejectNonStandardBodyWrites: false,
                                            _events: [Object: null prototype],
                                                _eventsCount: 4,
                                                    _maxListeners: undefined,
                                                        _connections: 1,
                                                            _handle: [TCP],
                                                                _usingWorkers: false,
                                                                    _workers: [],
                                                                        _unref: false,
                                                                            allowHalfOpen: true,
                                                                                pauseOnConnect: false,
                                                                                    noDelay: true,
                                                                                        keepAlive: false,
                                                                                            keepAliveInitialDelay: 0,
                                                                                                highWaterMark: 16384,
                                                                                                    httpAllowHalfOpen: false,
                                                                                                        timeout: 0,
                                                                                                            maxHeadersCount: null,
                                                                                                                maxRequestsPerSocket: 0,
                                                                                                                    _connectionKey: '6::::3000',
                                                                                                                        [Symbol(IncomingMessage)]: [Function: IncomingMessage],
                                                                                                                            [Symbol(ServerResponse)]: [Function: ServerResponse],
                                                                                                                                [Symbol(kCapture)]: false,
                                                                                                                                    [Symbol(async_id_symbol)]: 5,
                                                                                                                                        [Symbol(kUniqueHeaders)]: null,
                                                                                                                                            [Symbol(http.server.connections)]: ConnectionsList { },
            [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
                _idleTimeout: 30000,
                    _idlePrev: [TimersList],
                        _idleNext: [TimersList],
                            _idleStart: 428,
                                _onTimeout: [Function: bound checkConnections],
                                    _timerArgs: undefined,
                                        _repeat: 30000,
                                            _destroyed: false,
                                                [Symbol(refed)]: false,
                                                    [Symbol(kHasPrimitive)]: false,
                                                        [Symbol(asyncId)]: 7,
                                                            [Symbol(triggerId)]: 6
            }
        },
        _server: Server {
            maxHeaderSize: undefined,
                insecureHTTPParser: undefined,
                    requestTimeout: 300000,
                        headersTimeout: 60000,
                            keepAliveTimeout: 5000,
                                connectionsCheckingInterval: 30000,
                                    joinDuplicateHeaders: undefined,
                                        rejectNonStandardBodyWrites: false,
                                            _events: [Object: null prototype],
                                                _eventsCount: 4,
                                                    _maxListeners: undefined,
                                                        _connections: 1,
                                                            _handle: [TCP],
                                                                _usingWorkers: false,
                                                                    _workers: [],
                                                                        _unref: false,
                                                                            allowHalfOpen: true,
                                                                                pauseOnConnect: false,
                                                                                    noDelay: true,
                                                                                        keepAlive: false,
                                                                                            keepAliveInitialDelay: 0,
                                                                                                highWaterMark: 16384,
                                                                                                    httpAllowHalfOpen: false,
                                                                                                        timeout: 0,
                                                                                                            maxHeadersCount: null,
                                                                                                                maxRequestsPerSocket: 0,
                                                                                                                    _connectionKey: '6::::3000',
                                                                                                                        [Symbol(IncomingMessage)]: [Function: IncomingMessage],
                                                                                                                            [Symbol(ServerResponse)]: [Function: ServerResponse],
                                                                                                                                [Symbol(kCapture)]: false,
                                                                                                                                    [Symbol(async_id_symbol)]: 5,
                                                                                                                                        [Symbol(kUniqueHeaders)]: null,
                                                                                                                                            [Symbol(http.server.connections)]: ConnectionsList { },
            [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
                _idleTimeout: 30000,
                    _idlePrev: [TimersList],
                        _idleNext: [TimersList],
                            _idleStart: 428,
                                _onTimeout: [Function: bound checkConnections],
                                    _timerArgs: undefined,
                                        _repeat: 30000,
                                            _destroyed: false,
                                                [Symbol(refed)]: false,
                                                    [Symbol(kHasPrimitive)]: false,
                                                        [Symbol(asyncId)]: 7,
                                                            [Symbol(triggerId)]: 6
            }
        },
        parser: HTTPParser {
            '0': null,
                '1': [Function: parserOnHeaders],
                    '2': [Function: parserOnHeadersComplete],
                        '3': [Function: parserOnBody],
                            '4': [Function: parserOnMessageComplete],
                                '5': [Function: bound onParserExecute],
                                    '6': [Function: bound onParserTimeout],
                                        _headers: [],
                                            _url: '',
                                                socket: [Circular * 1],
                                                    incoming: [Circular * 2],
                                                        outgoing: null,
                                                            maxHeaderPairs: 2000,
                                                                _consumed: true,
                                                                    onIncoming: [Function: bound parserOnIncoming],
                                                                        joinDuplicateHeaders: null,
                                                                            [Symbol(resource_symbol)]: [HTTPServerAsyncResource]
        },
        on: [Function: socketListenerWrap],
            addListener: [Function: socketListenerWrap],
                prependListener: [Function: socketListenerWrap],
                    setEncoding: [Function: socketSetEncoding],
                        _paused: false,
                            _httpMessage: ServerResponse {
            _events: [Object: null prototype],
                _eventsCount: 2,
                    _maxListeners: undefined,
                        outputData: [],
                            outputSize: 0,
                                writable: true,
                                    destroyed: false,
                                        _last: false,
                                            chunkedEncoding: false,
                                                shouldKeepAlive: true,
                                                    maxRequestsOnConnectionReached: false,
                                                        _defaultKeepAlive: true,
                                                            useChunkedEncodingByDefault: true,
                                                                sendDate: true,
                                                                    _removedConnection: false,
                                                                        _removedContLen: false,
                                                                            _removedTE: false,
                                                                                strictContentLength: false,
                                                                                    _contentLength: null,
                                                                                        _hasBody: true,
                                                                                            _trailer: '',
                                                                                                finished: false,
                                                                                                    _headerSent: false,
                                                                                                        _closed: false,
                                                                                                            socket: [Circular * 1],
                                                                                                                _header: null,
                                                                                                                    _keepAliveTimeout: 5000,
                                                                                                                        _onPendingData: [Function: bound updateOutgoingData],
                                                                                                                            req: [Circular * 2],
                                                                                                                                _sent100: false,
                                                                                                                                    _expect_continue: false,
                                                                                                                                        _maxRequestsPerSocket: 0,
                                                                                                                                            locals: [Object: null prototype] { },
            _startAt: undefined,
                _startTime: undefined,
                    writeHead: [Function: writeHead],
                        __onFinished: [Function],
                            [Symbol(kCapture)]: false,
                                [Symbol(kBytesWritten)]: 0,
                                    [Symbol(kNeedDrain)]: false,
                                        [Symbol(corked)]: 0,
                                            [Symbol(kOutHeaders)]: [Object: null prototype],
                                                [Symbol(errored)]: null,
                                                    [Symbol(kHighWaterMark)]: 16384,
                                                        [Symbol(kRejectNonStandardBodyWrites)]: false,
                                                            [Symbol(kUniqueHeaders)]: null
        },
        _peername: { address: '::ffff:127.0.0.1', family: 'IPv6', port: 49456 },
        [Symbol(async_id_symbol)]: 104,
            [Symbol(kHandle)]: TCP {
            reading: true,
                onconnection: null,
                    _consumed: true,
                        [Symbol(owner_symbol)]: [Circular * 1]
        },
        [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(timeout)]: null,
                [Symbol(kBuffer)]: null,
                    [Symbol(kBufferCb)]: null,
                        [Symbol(kBufferGen)]: null,
                            [Symbol(kCapture)]: false,
                                [Symbol(kSetNoDelay)]: true,
                                    [Symbol(kSetKeepAlive)]: false,
                                        [Symbol(kSetKeepAliveInitialDelay)]: 0,
                                            [Symbol(kBytesRead)]: 0,
                                                [Symbol(kBytesWritten)]: 0
    },
    httpVersionMajor: 1,
        httpVersionMinor: 1,
            httpVersion: '1.1',
                complete: true,
                    rawHeaders: [
                        'Host',
                        '127.0.0.1:3000',
                        'Connection',
                        'keep-alive',
                        'Content-Length',
                        '0',
                        'Cache-Control',
                        'max-age=0',
                        'sec-ch-ua',
                        '"Chromium";v="122", "Not(A:Brand";v="24", "Brave";v="122"',
                        'sec-ch-ua-mobile',
                        '?0',
                        'sec-ch-ua-platform',
                        '"Linux"',
                        'Upgrade-Insecure-Requests',
                        '1',
                        'Origin',
                        'http://127.0.0.1:3000',
                        'Content-Type',
                        'application/x-www-form-urlencoded',
                        'User-Agent',
                        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
                        'Accept',
                        'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
                        'Sec-GPC',
                        '1',
                        'Accept-Language',
                        'en-US,en',
                        'Sec-Fetch-Site',
                        'same-origin',
                        'Sec-Fetch-Mode',
                        'navigate',
                        'Sec-Fetch-User',
                        '?1',
                        'Sec-Fetch-Dest',
                        'document',
                        'Referer',
                        'http://127.0.0.1:3000/login',
                        'Accept-Encoding',
                        'gzip, deflate, br',
                        'Cookie',
                        'csrftoken=9rIpvfD8G6yEfScUhYWjwvNIPKxdbjMS; sessionid=yl03l98dwuooyb3kmfxyyfkfnrygg98i'
                    ],
                        rawTrailers: [],
                            joinDuplicateHeaders: null,
                                aborted: false,
                                    upgrade: false,
                                        url: '/signup',
                                            method: 'POST',
                                                statusCode: null,
                                                    statusMessage: null,
                                                        client: <ref * 1 > Socket {
        connecting: false,
            _hadError: false,
                _parent: null,
                    _host: null,
                        _closeAfterHandlingError: false,
                            _readableState: ReadableState {
            state: 4184,
                highWaterMark: 16384,
                    buffer: BufferList { head: null, tail: null, length: 0 },
            length: 0,
                pipes: [],
                    flowing: true,
                        errored: null,
                            defaultEncoding: 'utf8',
                                awaitDrainWriters: null,
                                    decoder: null,
                                        encoding: null,
                                            [Symbol(kPaused)]: false
        },
        _events: [Object: null prototype] {
            end: [Array],
                timeout: [Function: socketOnTimeout],
                    data: [Function: bound socketOnData],
                        error: [Array],
                            close: [Array],
                                drain: [Function: bound socketOnDrain],
                                    resume: [Function: onSocketResume],
                                        pause: [Function: onSocketPause]
        },
        _eventsCount: 8,
            _maxListeners: undefined,
                _writableState: WritableState {
            objectMode: false,
                highWaterMark: 16384,
                    finalCalled: false,
                        needDrain: false,
                            ending: false,
                                ended: false,
                                    finished: false,
                                        destroyed: false,
                                            decodeStrings: false,
                                                defaultEncoding: 'utf8',
                                                    length: 0,
                                                        writing: false,
                                                            corked: 0,
                                                                sync: true,
                                                                    bufferProcessing: false,
                                                                        onwrite: [Function: bound onwrite],
                                                                            writecb: null,
                                                                                writelen: 0,
                                                                                    afterWriteTickInfo: null,
                                                                                        buffered: [],
                                                                                            bufferedIndex: 0,
                                                                                                allBuffers: true,
                                                                                                    allNoop: true,
                                                                                                        pendingcb: 0,
                                                                                                            constructed: true,
                                                                                                                prefinished: false,
                                                                                                                    errorEmitted: false,
                                                                                                                        emitClose: false,
                                                                                                                            autoDestroy: true,
                                                                                                                                errored: null,
                                                                                                                                    closed: false,
                                                                                                                                        closeEmitted: false,
                                                                                                                                            [Symbol(kOnFinished)]: []
        },
        allowHalfOpen: true,
            _sockname: null,
                _pendingData: null,
                    _pendingEncoding: '',
                        server: Server {
            maxHeaderSize: undefined,
                insecureHTTPParser: undefined,
                    requestTimeout: 300000,
                        headersTimeout: 60000,
                            keepAliveTimeout: 5000,
                                connectionsCheckingInterval: 30000,
                                    joinDuplicateHeaders: undefined,
                                        rejectNonStandardBodyWrites: false,
                                            _events: [Object: null prototype],
                                                _eventsCount: 4,
                                                    _maxListeners: undefined,
                                                        _connections: 1,
                                                            _handle: [TCP],
                                                                _usingWorkers: false,
                                                                    _workers: [],
                                                                        _unref: false,
                                                                            allowHalfOpen: true,
                                                                                pauseOnConnect: false,
                                                                                    noDelay: true,
                                                                                        keepAlive: false,
                                                                                            keepAliveInitialDelay: 0,
                                                                                                highWaterMark: 16384,
                                                                                                    httpAllowHalfOpen: false,
                                                                                                        timeout: 0,
                                                                                                            maxHeadersCount: null,
                                                                                                                maxRequestsPerSocket: 0,
                                                                                                                    _connectionKey: '6::::3000',
                                                                                                                        [Symbol(IncomingMessage)]: [Function: IncomingMessage],
                                                                                                                            [Symbol(ServerResponse)]: [Function: ServerResponse],
                                                                                                                                [Symbol(kCapture)]: false,
                                                                                                                                    [Symbol(async_id_symbol)]: 5,
                                                                                                                                        [Symbol(kUniqueHeaders)]: null,
                                                                                                                                            [Symbol(http.server.connections)]: ConnectionsList { },
            [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
                _idleTimeout: 30000,
                    _idlePrev: [TimersList],
                        _idleNext: [TimersList],
                            _idleStart: 428,
                                _onTimeout: [Function: bound checkConnections],
                                    _timerArgs: undefined,
                                        _repeat: 30000,
                                            _destroyed: false,
                                                [Symbol(refed)]: false,
                                                    [Symbol(kHasPrimitive)]: false,
                                                        [Symbol(asyncId)]: 7,
                                                            [Symbol(triggerId)]: 6
            }
        },
        _server: Server {
            maxHeaderSize: undefined,
                insecureHTTPParser: undefined,
                    requestTimeout: 300000,
                        headersTimeout: 60000,
                            keepAliveTimeout: 5000,
                                connectionsCheckingInterval: 30000,
                                    joinDuplicateHeaders: undefined,
                                        rejectNonStandardBodyWrites: false,
                                            _events: [Object: null prototype],
                                                _eventsCount: 4,
                                                    _maxListeners: undefined,
                                                        _connections: 1,
                                                            _handle: [TCP],
                                                                _usingWorkers: false,
                                                                    _workers: [],
                                                                        _unref: false,
                                                                            allowHalfOpen: true,
                                                                                pauseOnConnect: false,
                                                                                    noDelay: true,
                                                                                        keepAlive: false,
                                                                                            keepAliveInitialDelay: 0,
                                                                                                highWaterMark: 16384,
                                                                                                    httpAllowHalfOpen: false,
                                                                                                        timeout: 0,
                                                                                                            maxHeadersCount: null,
                                                                                                                maxRequestsPerSocket: 0,
                                                                                                                    _connectionKey: '6::::3000',
                                                                                                                        [Symbol(IncomingMessage)]: [Function: IncomingMessage],
                                                                                                                            [Symbol(ServerResponse)]: [Function: ServerResponse],
                                                                                                                                [Symbol(kCapture)]: false,
                                                                                                                                    [Symbol(async_id_symbol)]: 5,
                                                                                                                                        [Symbol(kUniqueHeaders)]: null,
                                                                                                                                            [Symbol(http.server.connections)]: ConnectionsList { },
            [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
                _idleTimeout: 30000,
                    _idlePrev: [TimersList],
                        _idleNext: [TimersList],
                            _idleStart: 428,
                                _onTimeout: [Function: bound checkConnections],
                                    _timerArgs: undefined,
                                        _repeat: 30000,
                                            _destroyed: false,
                                                [Symbol(refed)]: false,
                                                    [Symbol(kHasPrimitive)]: false,
                                                        [Symbol(asyncId)]: 7,
                                                            [Symbol(triggerId)]: 6
            }
        },
        parser: HTTPParser {
            '0': null,
                '1': [Function: parserOnHeaders],
                    '2': [Function: parserOnHeadersComplete],
                        '3': [Function: parserOnBody],
                            '4': [Function: parserOnMessageComplete],
                                '5': [Function: bound onParserExecute],
                                    '6': [Function: bound onParserTimeout],
                                        _headers: [],
                                            _url: '',
                                                socket: [Circular * 1],
                                                    incoming: [Circular * 2],
                                                        outgoing: null,
                                                            maxHeaderPairs: 2000,
                                                                _consumed: true,
                                                                    onIncoming: [Function: bound parserOnIncoming],
                                                                        joinDuplicateHeaders: null,
                                                                            [Symbol(resource_symbol)]: [HTTPServerAsyncResource]
        },
        on: [Function: socketListenerWrap],
            addListener: [Function: socketListenerWrap],
                prependListener: [Function: socketListenerWrap],
                    setEncoding: [Function: socketSetEncoding],
                        _paused: false,
                            _httpMessage: ServerResponse {
            _events: [Object: null prototype],
                _eventsCount: 2,
                    _maxListeners: undefined,
                        outputData: [],
                            outputSize: 0,
                                writable: true,
                                    destroyed: false,
                                        _last: false,
                                            chunkedEncoding: false,
                                                shouldKeepAlive: true,
                                                    maxRequestsOnConnectionReached: false,
                                                        _defaultKeepAlive: true,
                                                            useChunkedEncodingByDefault: true,
                                                                sendDate: true,
                                                                    _removedConnection: false,
                                                                        _removedContLen: false,
                                                                            _removedTE: false,
                                                                                strictContentLength: false,
                                                                                    _contentLength: null,
                                                                                        _hasBody: true,
                                                                                            _trailer: '',
                                                                                                finished: false,
                                                                                                    _headerSent: false,
                                                                                                        _closed: false,
                                                                                                            socket: [Circular * 1],
                                                                                                                _header: null,
                                                                                                                    _keepAliveTimeout: 5000,
                                                                                                                        _onPendingData: [Function: bound updateOutgoingData],
                                                                                                                            req: [Circular * 2],
                                                                                                                                _sent100: false,
                                                                                                                                    _expect_continue: false,
                                                                                                                                        _maxRequestsPerSocket: 0,
                                                                                                                                            locals: [Object: null prototype] { },
            _startAt: undefined,
                _startTime: undefined,
                    writeHead: [Function: writeHead],
                        __onFinished: [Function],
                            [Symbol(kCapture)]: false,
                                [Symbol(kBytesWritten)]: 0,
                                    [Symbol(kNeedDrain)]: false,
                                        [Symbol(corked)]: 0,
                                            [Symbol(kOutHeaders)]: [Object: null prototype],
                                                [Symbol(errored)]: null,
                                                    [Symbol(kHighWaterMark)]: 16384,
                                                        [Symbol(kRejectNonStandardBodyWrites)]: false,
                                                            [Symbol(kUniqueHeaders)]: null
        },
        _peername: { address: '::ffff:127.0.0.1', family: 'IPv6', port: 49456 },
        [Symbol(async_id_symbol)]: 104,
            [Symbol(kHandle)]: TCP {
            reading: true,
                onconnection: null,
                    _consumed: true,
                        [Symbol(owner_symbol)]: [Circular * 1]
        },
        [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(timeout)]: null,
                [Symbol(kBuffer)]: null,
                    [Symbol(kBufferCb)]: null,
                        [Symbol(kBufferGen)]: null,
                            [Symbol(kCapture)]: false,
                                [Symbol(kSetNoDelay)]: true,
                                    [Symbol(kSetKeepAlive)]: false,
                                        [Symbol(kSetKeepAliveInitialDelay)]: 0,
                                            [Symbol(kBytesRead)]: 0,
                                                [Symbol(kBytesWritten)]: 0
    },
    _consuming: false,
        _dumped: false,
            next: [Function: next],
                baseUrl: '',
                    originalUrl: '/signup',
                        _parsedUrl: Url {
        protocol: null,
            slashes: null,
                auth: null,
                    host: null,
                        port: null,
                            hostname: null,
                                hash: null,
                                    search: null,
                                        query: null,
                                            pathname: '/signup',
                                                path: '/signup',
                                                    href: '/signup',
                                                        _raw: '/signup'
    },
    params: { },
    query: { },
    res: <ref * 3 > ServerResponse {
        _events: [Object: null prototype] {
            finish: [Array],
                end: [Function: onevent]
        },
        _eventsCount: 2,
            _maxListeners: undefined,
                outputData: [],
                    outputSize: 0,
                        writable: true,
                            destroyed: false,
                                _last: false,
                                    chunkedEncoding: false,
                                        shouldKeepAlive: true,
                                            maxRequestsOnConnectionReached: false,
                                                _defaultKeepAlive: true,
                                                    useChunkedEncodingByDefault: true,
                                                        sendDate: true,
                                                            _removedConnection: false,
                                                                _removedContLen: false,
                                                                    _removedTE: false,
                                                                        strictContentLength: false,
                                                                            _contentLength: null,
                                                                                _hasBody: true,
                                                                                    _trailer: '',
                                                                                        finished: false,
                                                                                            _headerSent: false,
                                                                                                _closed: false,
                                                                                                    socket: <ref * 1 > Socket {
            connecting: false,
                _hadError: false,
                    _parent: null,
                        _host: null,
                            _closeAfterHandlingError: false,
                                _readableState: [ReadableState],
                                    _events: [Object: null prototype],
                                        _eventsCount: 8,
                                            _maxListeners: undefined,
                                                _writableState: [WritableState],
                                                    allowHalfOpen: true,
                                                        _sockname: null,
                                                            _pendingData: null,
                                                                _pendingEncoding: '',
                                                                    server: [Server],
                                                                        _server: [Server],
                                                                            parser: [HTTPParser],
                                                                                on: [Function: socketListenerWrap],
                                                                                    addListener: [Function: socketListenerWrap],
                                                                                        prependListener: [Function: socketListenerWrap],
                                                                                            setEncoding: [Function: socketSetEncoding],
                                                                                                _paused: false,
                                                                                                    _httpMessage: [Circular * 3],
                                                                                                        _peername: [Object],
                                                                                                            [Symbol(async_id_symbol)]: 104,
                                                                                                                [Symbol(kHandle)]: [TCP],
                                                                                                                    [Symbol(lastWriteQueueSize)]: 0,
                                                                                                                        [Symbol(timeout)]: null,
                                                                                                                            [Symbol(kBuffer)]: null,
                                                                                                                                [Symbol(kBufferCb)]: null,
                                                                                                                                    [Symbol(kBufferGen)]: null,
                                                                                                                                        [Symbol(kCapture)]: false,
                                                                                                                                            [Symbol(kSetNoDelay)]: true,
                                                                                                                                                [Symbol(kSetKeepAlive)]: false,
                                                                                                                                                    [Symbol(kSetKeepAliveInitialDelay)]: 0,
                                                                                                                                                        [Symbol(kBytesRead)]: 0,
                                                                                                                                                            [Symbol(kBytesWritten)]: 0
        },
        _header: null,
            _keepAliveTimeout: 5000,
                _onPendingData: [Function: bound updateOutgoingData],
                    req: [Circular * 2],
                        _sent100: false,
                            _expect_continue: false,
                                _maxRequestsPerSocket: 0,
                                    locals: [Object: null prototype] { },
        _startAt: undefined,
            _startTime: undefined,
                writeHead: [Function: writeHead],
                    __onFinished: [Function: listener] { queue: [Array] },
        [Symbol(kCapture)]: false,
            [Symbol(kBytesWritten)]: 0,
                [Symbol(kNeedDrain)]: false,
                    [Symbol(corked)]: 0,
                        [Symbol(kOutHeaders)]: [Object: null prototype] { 'x-powered-by': [Array] },
        [Symbol(errored)]: null,
            [Symbol(kHighWaterMark)]: 16384,
                [Symbol(kRejectNonStandardBodyWrites)]: false,
                    [Symbol(kUniqueHeaders)]: null
    },
    _startAt: [5592, 806051928],
        _startTime: 2024-03-05T21: 26: 56.572Z,
            _remoteAddress: '::ffff:127.0.0.1',
                body: { },
    _body: true,
        length: undefined,
            secret: undefined,
                cookies: {
        csrftoken: '9rIpvfD8G6yEfScUhYWjwvNIPKxdbjMS',
            sessionid: 'yl03l98dwuooyb3kmfxyyfkfnrygg98i'
    },
    signedCookies: [Object: null prototype] { },
    route: Route {
        path: '/signup',
            stack: [[Layer]],
                methods: { post: true }
    },
    [Symbol(kCapture)]: false,
        [Symbol(kHeaders)]: {
        host: '127.0.0.1:3000',
            connection: 'keep-alive',
                'content-length': '0',
                    'cache-control': 'max-age=0',
                        'sec-ch-ua': '"Chromium";v="122", "Not(A:Brand";v="24", "Brave";v="122"',
                            'sec-ch-ua-mobile': '?0',
                                'sec-ch-ua-platform': '"Linux"',
                                    'upgrade-insecure-requests': '1',
                                        origin: 'http://127.0.0.1:3000',
                                            'content-type': 'application/x-www-form-urlencoded',
                                                'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
                                                    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
                                                        'sec-gpc': '1',
                                                            'accept-language': 'en-US,en',
                                                                'sec-fetch-site': 'same-origin',
                                                                    'sec-fetch-mode': 'navigate',
                                                                        'sec-fetch-user': '?1',
                                                                            'sec-fetch-dest': 'document',
                                                                                referer: 'http://127.0.0.1:3000/login',
                                                                                    'accept-encoding': 'gzip, deflate, br',
                                                                                        cookie: 'csrftoken=9rIpvfD8G6yEfScUhYWjwvNIPKxdbjMS; sessionid=yl03l98dwuooyb3kmfxyyfkfnrygg98i'
    },
    [Symbol(kHeadersCount)]: 42,
        [Symbol(kTrailers)]: null,
            [Symbol(kTrailersCount)]: 0
}


